# {pass: yes, timeout: 300}
- testgendata:
    version: '1.0.0'
    primarykey:
      name: 'inline'
      first: 1
      last: 1
      step: 1
    secondarykey:
      name: 'crossline'
      first: 11
      last: 20
      step: 2
    tracekey:
      name: 'samples'
      tmin: 1000
      tmax: 13000
      length: 25
      unit: ms
      data:
        sequence:
          type: int32
          min: 100
          max: 100
          step: 0
- mute:
    version: '1.0.0'
    compare_direction: '<'
    threshold:
      value: 3000
    tapering_window_size: 2000
- mute:
    version: '1.0.0'
    compare_direction: '>'
    threshold:
      value: 9000
    tapering_window_size: 2000
- testexpect:
    version: '1.0.0'
    primarykey:
      name: 'inline'
      first: 1
      last: 1
      step: 1
    secondarykey:
      name: 'crossline'
      first: 11
      last: 20
      step: 2
    tracekey:
      name: 'samples'
      tmin: 1000
      tmax: 13000
      length: 25
      unit: ms
      type: int32
      pattern: MUTE_3000_9000_PLUS_2000
