- testgendata:
    version: '1.0.0'
    primarykey:
      name: 'inline'
      first: 1
      last: 10
      step: 1
    secondarykey:
      name: 'crossline'
      first: 1
      last: 10
      step: 1
    tracekey:
      name: 'samples'
      tmin: 0
      tmax: 5000
      length: 16
      unit: ms
      data:
        random:
          type: float
          min: -1
          max: 1          
    attribute:
    - name: attr1
      unit: m
      length: 1
      data:
        random:
          type: int
          min: 0
          max: 100        
    - name: attr2
      unit: ms
      length: 1
      data:
        sequence:
          type: float
          min: 0
          max: 100
          step: 0.3 
- testexpect:
    version: '1.0.0'
    primarykey:
      name: 'inline'
      first: 1
      last: 10
      step: 1
    secondarykey:
      name: 'crossline'
      first: 1
      last: 10
      step: 1
    tracekey:
      name: 'samples'
      tmin: 0
      tmax: 5000
      length: 16
      unit: ms
      type: float
      pattern: SAME
    attribute:
    - name: attr1
      unit: m
      length: 1
      type: int
      pattern: SAME
    - name: attr2
      unit: ms
      length: 1
      data:
      type: float
      pattern: SAME


