# {"pass":"no"}
- testgendata:
    version: '1.0.0'
    primarykey:
      name: 'inline'
      first: 1
      last: 10
      step: 1
    secondarykey:
      name: 'crossline'
      first: 1
      last: 10
      step: 1
    tracekey:
      name: 'samples'
      tmin: 0
      tmax: 5000
      length: 16
      unit: ms
      data:
        random:
          type: float
          min: -1
          max: 1          
    attribute:
- attrcalc:
    version: '1.1.0'
    attrname: 'ATTR1'
    type: 'float'
    action: 'create'
    expr: 'inline+samples*2.7'                  
- testexpect:
    version: '1.0.0'
    primarykey:
      name: 'inline'
      first: 1
      last: 10
      step: 1
    secondarykey:
      name: 'crossline'
      first: 1
      last: 10
      step: 1
    tracekey:
      name: 'samples'
      tmin: 0
      tmax: 5000
      length: 16
      unit: ms
      type: float
      pattern: SAME
    attribute:
    - name: attr1
      unit: m
      length: 1
      type: float
      pattern: 'INLINE+CROSSline*2.7'


