# {pass: no, timeout: 300, log: ["check data failed."]}
# Test different input parameter  - should fail parsing
- testgendata:
    version: '1.0.0'
    primarykey:
      name: 'inline'
      first: 1
      last: 10
      step: 1
    secondarykey:
      name: 'crossline'
      first: 1
      last: 10
      step: 1
    tracekey:
      name: 'samples'
      tmin: 0
      tmax: 5000
      length: 1001
      unit: ms
      data:
        random:
          type: float
          min: -1
          max: 1
- scale:
    version: '1.0.0'
    method:
      - agc:
          window_size: 100         # In testexpect_scale.py, the value of 'window_size' is 500
- testexpect:
    version: '1.0.0'
    primarykey:
      name: 'inline'
      first: 1
      last: 10
      step: 1
    secondarykey:
      name: 'crossline'
      first: 1
      last: 10
      step: 1
    tracekey:
      name: 'samples'
      tmin: 0
      tmax: 5000
      length: 1001
      unit: ms
      type: float
      pattern: SCALE_AGC