# {pass: no, timeout: 300, log: ["set factor.value with different value"]}
# Test different input parameter  - should fail parsing
# {pass: yes, timeout: 300}
- testgendata:
    version: '1.0.0'
    primarykey:
      name: 'inline'
      first: 1
      last: 10
      step: 1
    secondarykey:
      name: 'crossline'
      first: 1
      last: 10
      step: 1
    tracekey:
      name: 'samples'
      tmin: 0
      tmax: 5000
      length: 1001
      unit: ms
      data:
        random:
          type: float
          min: -1
          max: 1          
    attribute:
- scale:
    version: '1.0.0'
    method:
      - factor: 
          value: 0.1              # In testexpect_scale.py, the value of 'value' is 0.5
- testexpect:
    version: '1.0.0'
    primarykey:
      name: 'inline'
      first: 1
      last: 10
      step: 1
    secondarykey:
      name: 'crossline'
      first: 1
      last: 10
      step: 1
    tracekey:
      name: 'samples'
      tmin: 0
      tmax: 5000
      length: 1001
      unit: ms
      type: float
      pattern: SCALE_FACTOR